routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function() {
    return view('home');
});

Route::resource('/karyawan', 'KaryawanController');
Route::resource('/grade', 'GradeController');

app/Models/Grade.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Grade extends Model
{
    protected $table = 'grade';
    protected $fillable = [
        'grade',
        'gaji'
    ];
    
    public function karyawan() {
        return $this->hasMany(Karyawan::class);
    }

    public function getGajiAttribute($value) {
        return number_format($value, 0);
    }
}

app/Models/Karyawan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Karyawan extends Model
{
    protected $table = 'karyawan';
    protected $fillable = [
        'nip',
        'nama',
        'is_male',
        'is_female',
        'tanggal_lahir',
        'tanggal_masuk',
        'grade_id',
        'jenis_kelamin'
    ];

    protected $appends = [
        'jenis_kelamin'
    ];

    public function grade() {
        return $this->belongsTo(Grade::class);
    }

    public function getJenisKelaminAttribute() {
        if($this->is_male) {
            return 'M';
        }
        else if($this->is_female) {
            return 'F';
        }
    }

    public function setJenisKelaminAttribute($value) {
        if($value === 'male') {
            $this->attributes['is_male'] = true;
            $this->attributes['is_female'] = false;
        }
        else if($value === 'female') {
            $this->attributes['is_male'] = false;
            $this->attributes['is_female'] = true;
        }
    }

    public function scopeFilter($query, $request) {
        if($request->has('search')) {
            $query->where('nama', 'like', '%' . $request->search . '%')
                  ->orWhere('nip', $request->search);
        }

        if($request->has('dari_tanggal') && $request->has('sampai_tanggal')) {
            $query->whereDate('tanggal_masuk', '>=', $request->dari_tanggal)
                  ->whereDate('tanggal_masuk', '<=', $request->sampai_tanggal);
        }
        return $query;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GradeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Grade;

class GradeController extends Controller
{
    public function index() {
        $grade = Grade::get([
            'id',
            'grade',
            'gaji'
        ]);
        return view('grade.index', ['grade' => $grade]);
    }

    public function create() {
        return view('grade.create');
    }

    public function store(Request $request) {
        $request->validate([
            'grade' => 'required|max:1|unique:grade',
            'gaji' => 'required|numeric'
        ]);
        $grade = Grade::create($request->all());
        return redirect()->route('grade.create')->with(['message' => 'Grade berhasil ditambah']);
    }

    public function edit($id) {
        $grade = Grade::find($id);
        return view('grade.edit', ['grade' => $grade]);
    }

    public function update(Request $request, $id) {
        $request->validate([
            'grade' => 'required|max:1|unique:grade,grade,' . $id,
            'gaji' => 'required|numeric'
        ]);
        $grade = Grade::find($id);
        $grade->update($request->all());
        return redirect()->route('grade.index')->with(['message' => 'Grade berhasil diupdate']);
    }

    public function destroy($id) {
        $grade = Grade::with('karyawan')->findOrFail($id);
        if($grade->karyawan->count() > 0) {
            return redirect()->route('grade.index')->with(['message' => 'Grade berelasi tidak dapat dihapus']);
        }
        else {
            $grade->delete();
            return redirect()->route('grade.index')->with(['message' => 'Grade berhasil dihapus']);
        }
    }
}

app/Http/Controllers/KaryawanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Karyawan;
use App\Models\Grade;

class KaryawanController extends Controller
{
    public function index(Request $request) {
        $karyawan = Karyawan::with('grade:id,grade,gaji')->filter($request)->get([
            'id',
            'nip',
            'nama',
            'is_male',
            'is_female',
            'tanggal_lahir',
            'tanggal_masuk',
            'grade_id',
        ]);
        return view('karyawan.index', ['karyawan' => $karyawan]);
    }

    public function create() {
        $grade = Grade::get(['id', 'grade', 'gaji']);
        return view('karyawan.create', ['grade' => $grade]);
    }

    public function store(Request $request) {
        $request->validate([
            'nip' => 'required|numeric|unique:karyawan',
            'nama' => 'required|max:255',
            'jenis_kelamin' => 'required',
            'tanggal_lahir' => 'required|date',
            'grade_id' => 'required|numeric'
        ]);
        $request->merge(['tanggal_masuk' => date('Y-m-d')]);
        $karyawan = Karyawan::create($request->all());
        return redirect()->route('karyawan.create')->with(['message' => 'Karyawan berhasil ditambah']);
    }

    public function edit($id) {
        $karyawan = Karyawan::find($id);
        $grade = Grade::get(['id', 'grade', 'gaji']);
        return view('karyawan.edit', ['karyawan' => $karyawan, 'grade' => $grade]);
    }

    public function update(Request $request, $id) {
        $request->validate([
            'nip' => 'required|numeric|unique:karyawan,nip,'. $id,
            'nama' => 'required|max:255',
            'jenis_kelamin' => 'required',
            'tanggal_lahir' => 'required|date',
            'grade_id' => 'required|numeric'
        ]);

        $karyawan = Karyawan::find($id);
        $karyawan->update($request->all());
        return redirect()->route('karyawan.index')->with(['message' => 'Karyawan berhasil diupdate']);
    }

    public function destroy($id) {
        $karyawan = Karyawan::find($id);
        $karyawan->delete();
        return redirect()->route('karyawan.index')->with(['message' => 'Karyawan berhasil di hapus']);
    }
}

resources/views/grade/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
      <div class="col">
        <h2>Tambah Grade</h2>
      </div>
    </div>
    @if ($msg = Session::get('message'))
      <div class="alert alert-info alert-block">
        {{ $msg }}
      </div>
    @endif
    <div class="row justify-content-center">
        <div class="col">
            <div class="card">
                <div class="card-header">
                  Tambah Grade
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('grade.store') }}">
                      @csrf
                        <div class="form-group">
                          <label for="grade">Grade</label>
                          <input name="grade" type="text" class="form-control @error('grade') is-invalid @enderror" value="{{ old('grade') }}" id="grade" aria-describedby="grade" placeholder="Masukkan grade">
                          @error('grade')
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                          @enderror
                        </div>
                        <div class="form-group">
                            <label for="gaji">Gaji</label>
                            <input name="gaji" type="number" class="form-control @error('gaji') is-invalid @enderror" value="{{ old('gaji') }}" id="gaji" aria-describedby="gaji" placeholder="Masukkan gaji">
                            @error('gaji')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group text-right">
                          <a class="btn btn-danger" href="{{ route('grade.index') }}">Cancel</a>
                          <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
              </div>
        </div>
    </div>
</div>

<script>
    $('.tgl').datepicker({
      dateFormat: 'yy-mm-dd'
    });
</script>
@endsection

resources/views/grade/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
      <div class="col">
        <h2>Edit Grade</h2>
      </div>
    </div>
    @if ($msg = Session::get('message'))
      <div class="alert alert-info alert-block">
        {{ $msg }}
      </div>
    @endif
    <div class="row justify-content-center">
        <div class="col">
            <div class="card">
                <div class="card-header">
                  Edit Grade
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('grade.update', $grade->id) }}">
                      @csrf
                      @method('PATCH')
                        <div class="form-group">
                          <label for="grade">Grade</label>
                          <input name="grade" type="text" class="form-control @error('grade') is-invalid @enderror" value="{{ $grade->grade }}" id="grade" aria-describedby="grade" placeholder="Masukkan grade">
                          @error('grade')
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                          @enderror
                        </div>
                        <div class="form-group">
                            <label for="gaji">Gaji</label>
                            <input name="gaji" type="number" class="form-control @error('gaji') is-invalid @enderror" value="{{ filter_var($grade->gaji, FILTER_SANITIZE_NUMBER_INT) }}" id="gaji" aria-describedby="gaji" placeholder="Masukkan gaji">
                            @error('gaji')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group text-right">
                          <a class="btn btn-danger" href="{{ route('grade.index') }}">Cancel</a>
                          <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
              </div>
        </div>
    </div>
</div>

<script>
    $('.tgl').datepicker({
      dateFormat: 'yy-mm-dd'
    });
</script>
@endsection

resources/views/grade/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
      <div class="col">
        <h2>List Grade</h2>
      </div>
      <div class="col-auto">
        <a class="btn btn-primary" href="{{ route('grade.create') }}">Tambah Grade +</a>
      </div>
    </div>
    @if ($msg = Session::get('message'))
      <div class="alert alert-info alert-block">
        {{ $msg }}
      </div>
    @endif
    <div class="row justify-content-center">
        <div class="col">
            <div class="table-responsive">
                <table class="table table-striped" id="tbl">
                  <thead class="thead-dark">
                    <tr class="text-center">
                      <th scope="col">Grade</th>
                      <th scope="col">Gaji</th>
                      <th scope="col">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($grade as $gr)
                      <tr class="text-center">
                        <th scope="row">{{ $gr->grade }}</th>
                        <td>{{ $gr->gaji }}</td>
                        <td class="d-flex justify-content-center">
                          <a href="{{ route('grade.edit', $gr->id) }}" class="btn btn-primary btn-sm">Edit</a>
                          <form method="POST" action="{{ route('grade.destroy', $gr->id) }}">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-danger btn-sm mx-1">Delete</button>
                          </form>
                        </td>
                      </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/karyawan/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
      <div class="col">
        <h2>Tambah Karyawan</h2>
      </div>
    </div>
    @if ($msg = Session::get('message'))
      <div class="alert alert-info alert-block">
        {{ $msg }}
      </div>
    @endif
    <div class="row justify-content-center">
        <div class="col">
            <div class="card">
                <div class="card-header">
                  Tambah Karyawan
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('karyawan.store') }}">
                      @csrf
                        <div class="form-group">
                          <label for="nip">NIP</label>
                          <input name="nip" type="number" class="form-control @error('nip') is-invalid @enderror" value="{{ old('nip') }}" id="nip" aria-describedby="nip" placeholder="Masukkan NIP">
                          @error('nip')
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                          @enderror
                        </div>
                        <div class="form-group">
                            <label for="nama">Nama</label>
                            <input name="nama" type="text" class="form-control @error('nama') is-invalid @enderror" value="{{ old('nama') }}" id="nama" aria-describedby="nama" placeholder="Masukkan nama">
                            @error('nama')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="jenis_kelamin">Jenis Kelamin</label>
                            <select class="form-control @error('jenis_kelamin') is-invalid @enderror" id="jenis_kelamin" name="jenis_kelamin">
                              <option disabled selected hidden>Pilih jenis kelamin</option>
                              <option value="male" {{ (old('jenis_kelamin') === "male") ? 'selected' : '' }}>Laki-laki</option>
                              <option value="female" {{ (old('jenis_kelamin') === "female") ? 'selected' : '' }}>Perempuan</option>
                            </select>
                            @error('jenis_kelamin')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="tanggal_lahir">Tanggal Lahir</label>
                            <input name="tanggal_lahir" type="text" class="form-control tgl @error('tanggal_lahir') is-invalid @enderror" value="{{ old('tanggal_lahir') }}" id="tanggal_lahir" aria-describedby="tanggal lahir" placeholder="Masukkan tanggal_lahir">
                            @error('tanggal_lahir')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="grade">Grade</label>
                            <select class="form-control @error('grade_id') is-invalid @enderror" id="grade" name="grade_id">
                              <option disabled selected hidden>Pilih grade</option>
                              @foreach ($grade as $gr)
                                  <option 
                                    value="{{ $gr->id }}"
                                    {{ (old('grade_id') == $gr->id) ? 'selected' : '' }}
                                  >
                                    {{ $gr->grade }} - {{ $gr->gaji }}
                                  </option>
                              @endforeach
                            </select>
                            @error('gracde_id')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group text-right">
                          <a class="btn btn-danger" href="{{ route('karyawan.index') }}">Cancel</a>
                          <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
              </div>
        </div>
    </div>
</div>

<script>
    $('.tgl').datepicker({
      dateFormat: 'yy-mm-dd'
    });
</script>
@endsection

resources/views/karyawan/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
      <div class="col">
        <h2>Edit Karyawan</h2>
      </div>
    </div>
    @if ($msg = Session::get('message'))
      <div class="alert alert-info alert-block">
        {{ $msg }}
      </div>
    @endif
    <div class="row justify-content-center">
        <div class="col">
            <div class="card">
                <div class="card-header">
                  Edit Karyawan
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('karyawan.update', $karyawan->id) }}">
                      @method('PATCH')
                      @csrf
                        <div class="form-group">
                          <label for="nip">NIP</label>
                          <input name="nip" type="number" class="form-control @error('nip') is-invalid @enderror" value="{{ $karyawan->nip }}" id="nip" aria-describedby="nip" placeholder="Masukkan NIP">
                          @error('nip')
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                          @enderror
                        </div>
                        <div class="form-group">
                            <label for="nama">Nama</label>
                            <input name="nama" type="text" class="form-control @error('nama') is-invalid @enderror" value="{{ $karyawan->nama }}" id="nama" aria-describedby="nama" placeholder="Masukkan nama">
                            @error('nama')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="jenis_kelamin">Jenis Kelamin</label>
                            <select class="form-control @error('jenis_kelamin') is-invalid @enderror" id="jenis_kelamin" name="jenis_kelamin">
                              <option disabled selected hidden>Pilih jenis kelamin</option>
                              <option value="male" {{ ($karyawan->jenis_kelamin) === "M" ? 'selected' : '' }}>Laki-laki</option>
                              <option value="female" {{ ($karyawan->jenis_kelamin === "F") ? 'selected' : '' }}>Perempuan</option>
                            </select>
                            @error('jenis_kelamin')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="tanggal_lahir">Tanggal Lahir</label>
                            <input name="tanggal_lahir" type="text" class="form-control tgl @error('tanggal_lahir') is-invalid @enderror" value="{{ $karyawan->tanggal_lahir }}" id="tanggal_lahir" aria-describedby="tanggal lahir" placeholder="Masukkan tanggal_lahir">
                            @error('tanggal_lahir')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="grade">Grade</label>
                            <select class="form-control @error('grade_id') is-invalid @enderror" id="grade" name="grade_id">
                              <option disabled selected hidden>Pilih grade</option>
                              @foreach ($grade as $gr)
                                  <option 
                                    value="{{ $gr->id }}"
                                    {{ ($karyawan->grade_id == $gr->id) ? 'selected' : '' }}
                                  >
                                    {{ $gr->grade }} - {{ $gr->gaji }}
                                  </option>
                              @endforeach
                            </select>
                            @error('grade_id')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group text-right">
                            <a class="btn btn-danger" href="{{ route('karyawan.index') }}">Cancel</a>
                            <button type="submit" class="btn btn-primary">Submit</button>
                          </div>
                    </form>
                </div>
              </div>
        </div>
    </div>
</div>

<script>
    $('.tgl').datepicker({
      dateFormat: 'yy-mm-dd'
    });
</script>
@endsection

resources/views/karyawan/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center mb-2">
      <div class="col">
        <h2>List Karyawan</h2>
      </div>
      <div class="col-auto">
        <a class="btn btn-primary" href="{{ route('karyawan.create') }}">Tambah Karyawan +</a>
      </div>
    </div>
    @if ($msg = Session::get('message'))
      <div class="alert alert-info alert-block mb-2">
        {{ $msg }}
      </div>
    @endif
    <div class="row justify-content-center">
      <div class="col-auto">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#filterTglModal">
          Filter
        </button>
      </div>
      <div class="col">
          <form method="POST" action="{{ route('karyawan.index') }}" role="search">
            @csrf
            @method('GET')
            <div class="input-group mb-3">
              <input name="search" type="text" class="form-control" placeholder="Search..." aria-label="Search..." aria-describedby="button-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="submit" id="button-addon2">Search</button>
              </div>
          </div>
        </form>
      </div>
    </div>
    <div class="row justify-content-center">
        <div class="col">
            <div class="table-responsive">
                <table class="table table-striped" id="tbl">
                  <thead class="thead-dark">
                    <tr>
                      <th scope="col">NIP</th>
                      <th scope="col">Nama</th>
                      <th scope="col">Gender</th>
                      <th scope="col">Tgl Lahir</th>
                      <th scope="col">Tgl Masuk</th>
                      <th scope="col">Grade</th>
                      <th scope="col">Gaji</th>
                      <th scope="col">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($karyawan as $kr)
                      <tr>
                        <th scope="row">{{ $kr->nip }}</th>
                        <td>{{ $kr->nama }}</td>
                        <td>{{ $kr->jenis_kelamin }}</td>
                        <td>{{ $kr->tanggal_lahir }}</td>
                        <td>{{ $kr->tanggal_masuk }}</td>
                        <td>{{ $kr->grade->grade }}</td>
                        <td>{{ $kr->grade->gaji }}</td>
                        <td class="d-flex">
                          <a href="{{ route('karyawan.edit', $kr->id) }}" class="btn btn-primary btn-sm mx-1">Edit</a>
                          <form method="POST" action="{{ route('karyawan.destroy', $kr->id) }}">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-danger btn-sm mx-1">Delete</button>
                          </form>
                        </td>
                      </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="filterTglModal" tabindex="-1" role="dialog" aria-labelledby="filterTglModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="filterTglModalLabel">Filter</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form id="filterTgl" method="POST" action="{{ route('karyawan.index') }}">
              @csrf
              @method('GET')
                <div class="form-group">
                  <label for="dari_tanggal">Dari Tanggal</label>
                  <input name="dari_tanggal" type="text" class="form-control tgl" id="dari_tanggal" placeholder="Dari Tanggal">
                </div>
                <div class="form-group">
                  <label for="sampai_tanggal">Sampai Tanggal</label>
                  <input name="sampai_tanggal" type="text" class="form-control tgl" id="sampai_tanggal" placeholder="Sampai Tanggal">
                </div>
            </form>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary" form="filterTgl">Filter</button>
        </div>
      </div>
    </div>
  </div>

<script>
    $('.tgl').datepicker({
      dateFormat: 'yy-mm-dd'
    });
</script>
@endsection